directory/urls.py
from django.urls import path

from .views import add_contact, index, view_contact, volunteers

urlpatterns = [
    path('', index, name="home"),
    path('add', add_contact, name="add-contact"),
    path('view/<obj_type>/<int:pk>', view_contact, name="view-object"),
    path('view/volunteers/<vtype>', volunteers, name="view-volunteers"),
]

homeschool_connection/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

directory/models.py
from datetime import date
from django.db import models
from django.db.models.enums import Choices
from django.utils.translation import ugettext_lazy as _

from phonenumber_field.modelfields import PhoneNumberField

def participation_level_choices():
    return (
        ('a', 'All-In'),
        ('b', 'Email Me'),
        ('c', 'Usually Busy'),
    )

def contact_choices():
    return(
        ('e', 'Email'),
        ('p', 'Phone'),
        ('t', 'Text'),
        # ('s', 'Social Media Account'),
    )

def volunteering_types():
    return (
        ('Ft', 'Field Trips'),
        ('T', 'Tutoring'),
        ('S', 'Small Snack'),
        ('SG', 'Study Groups'),
    )

class ParentContact(models.Model):
    first_name = models.CharField(_("first name"), max_length=50)
    last_name = models.CharField(_("last name"), max_length=60)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)    
    phone_number = PhoneNumberField(_("phone number"),null=True, blank=True)
    email = models.EmailField(_("email"), max_length=254,null=True, blank=True)
    participation_level = models.CharField(_("participation level"), choices=participation_level_choices(), max_length=5)
    volunteering_type_1 = models.CharField(_("Volunteer Type 1"), max_length=5, choices=volunteering_types())
    volunteering_type_2 = models.CharField(_("Volunteer Type 2"), max_length=5, choices=volunteering_types())
    best_contact_option = models.CharField(_('best contact option'), choices=contact_choices(), max_length=5)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class Child(models.Model):
    first_name = models.CharField(_("first name"), max_length=50)
    last_name = models.CharField(_("last name"), max_length=50)
    birth_date = models.DateField()
    parent = models.ForeignKey("ParentContact", related_name="children", on_delete=models.CASCADE)
    allergies = models.TextField(null=True, blank=True)
    medical_notes = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    @property
    def child_name(self):
        return self.__str__()

    @property
    def age(self):
        today = date.today()
        try: 
            birthday = self.birth_date.replace(year=today.year)
        except ValueError: # raised when birth date is February 29 and the current year is not a leap year
            birthday =  self.birth_date.replace(year=today.year, month= self.birth_date.month+1, day=1)
        if birthday > today:
            return today.year -  self.birth_date.year - 1
        else:
            return today.year -  self.birth_date.year

    
    class Meta:
        verbose_name_plural = 'Children'
    

directory/forms.py
from django.forms import ModelForm
from django.forms import modelformset_factory
from django.forms.models import modelform_factory

from crispy_forms.helper import FormHelper, Layout

from .models import *

# class FamilyForm(ModelForm):
#     class Meta:
#         model = Family
#         fields = '__all__'


class ParentContactForm(ModelForm):
    class Meta:
        model = ParentContact
        fields = '__all__'


class ChildForm(ModelForm):
    class Meta:
        model = Child
        fields = ('first_name', 'last_name', 'birth_date', 'allergies', 'medical_notes')


class MyFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(MyFormSetHelper, self).__init__(*args, **kwargs)
        self.template = 'bootstrap/table_inline_formset.html'

directory/views.py
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory, formset_factory
from django.db.models import Count, Q
from django.utils.encoding import force_text

import random


from .models import *
from .forms import *
from .utils import get_vtypes

def _get_form(request, formcls, prefix):
    data = request.POST if prefix in request.POST else None
    return formcls(data, prefix=prefix)


def index(request):
    parents = ParentContact.objects.all()
    children = Child.objects.all()
    vtypes = {i[0]:i[1] for i in ParentContact._meta.get_field('volunteering_type_1').choices }
    t1 = ParentContact.objects.values('volunteering_type_1').annotate(count=Count('volunteering_type_1'))
    t2 = ParentContact.objects.values('volunteering_type_2').annotate(count=Count('volunteering_type_2'))
    context = {
        'parents':parents,
        'volunteer_types': get_vtypes(vtypes,t1,t2),
        'children': children
    }
    return render(request, "directory/home.html", context)


def view_contact(request, obj_type, pk):
    if obj_type == 'parent':
        parent = ParentContact.objects.prefetch_related('children').get(pk=pk)
    else:
        parent = ParentContact.objects.prefetch_related('children').get(children__pk=pk)
    context = {
        'parent': parent
    }
    return render(request, 'directory/view_contact.html', context)    


def volunteers(request, vtype):
    vtypes = {i[1]:i[0] for i in ParentContact._meta.get_field('volunteering_type_1').choices }
    value = vtypes[vtype]
    objs = ParentContact.objects.filter(Q(volunteering_type_1=value)|Q(volunteering_type_2=value))
    context = {'parents': objs, 'type': vtype}
    return render(request, 'directory/volunteer_list.html', context)    


def add_contact(request):
    if request.method == 'POST':
        parent_form = ParentContactForm(request.POST, prefix='parent')
        child_form = ChildForm(request.POST, prefix='child')
        if parent_form.is_valid() and child_form.is_valid:
            parent = parent_form.save()
            child = child_form.save(commit=False)
            child.parent = parent
            child.save()
            return redirect(index)
        else:
            print(parent_form.errors)
            print(child_form.errors)
    else:
        parent_form = ParentContactForm(prefix='parent')
        child_form = ChildForm(prefix='child')
        helper = MyFormSetHelper()
        context = {
            'parent_form': parent_form, 
            'child_form': child_form,
            'helper': helper
        }
        return render(request, 'directory/add_contact.html', context)
    

directory/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}
            HomeSchool Connections
            {% endblock title %}
        </title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet"/>
        {% comment %} {% load staticfiles %} {% endcomment %}
        {% comment %} <link rel="stylesheet" href="{% static 'main.css' %}"> {% endcomment %}
        <style>
            html, body {
                background:#1e3888;
            }
            h1 {
                color:white;
            }
            .card-title {
                margin-bottom: .75rem;
                color: white;
                font-weight: bolder;
                text-align: center;
            }
            .card-body {
                background-color: #fff;
            }
            .card-header {
                padding: .75rem 1.25rem;
                margin-bottom: 0;
                background-color: #47a8bd;
                border-bottom: 1px solid rgba(0,0,0,.125);
            }
            .card-header {
                background: #2d7cca;
            }
            .card {
                margin-bottom: 4px;
            }
            .search-card {
                max-height: 18rem;
            }
            .search-card ul.list-group.list-group-flush {
                height: 100%;
                overflow: auto;
            }
            .search-glass {
                font-family: FontAwesome;
            }
        </style>
    </head>
    <body>

        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
        <a class="navbar-brand" href="{% url 'home' %}">HSC</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavbar">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "add-contact" %}">Add Contact</a>
                </li>
            </ul>
        </div>  
        </nav>
        {% block sidebar %}

        {% endblock sidebar %}
        <div class="main container" style="margin-top:5px">
        {% block content %}
        {% endblock content %}
        </div>
        <div class="hidden">
        {% block javascript %}
        {% endblock javascript %}
        </div>
    </body>
</html>

directory/templates/directory/add_contact.html
{% extends 'base.html' %}

{% block title %}
Add Contact
{% endblock title %}

{% load crispy_forms_tags %}


{% block content %}
<form action="{% url "add-contact" %}" method="post">
    {% csrf_token %}
    <div class="row">
        <div class="container">
            <div class="card">
                <div class="card-header" >
                    <div class="card-title">Add Contact</div>
                </div>
                <div  class="card-body">    
                    <div class="card-body">
                        <div class="container">
                            {% include 'directory/parent-form.html' %}
                            <div class="row"><div class="container"><h6>Child Information</h6></div></div>
                            <hr>
                            {% include 'directory/child-form.html'  %}
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <button type="submit" class="float-right text-center btn btn-primary">Submit</button>
                </div>
            </div>
        </div> 
    </div>
</form>
{% endblock content %}

directory/templates/directory/child-form.html
<div class="row">
    <div class="col">
        <div class="form-group">
            <label for="child-child_name">Child Name<span class="asteriskField">*</span></label>
            <input type="text" name="child-child_name" maxlength="50" class="textinput textInput form-control" id="id_child-child_name">
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="child-birth_date">Birth Date<span class="asteriskField">*</span></label>
            <input type="date" name="child-birth_date" class="dateinput form-control" id="id_child-birth_date">
        </div>
    </div>
</div>
<div class="row">
    <div class="col">
        <div class="form-group">
        <label for="child-allergies">Allergies</label>
        <textarea name="child-allergies" cols="20" rows="3" class="textarea form-control" id="id_child-allergies"></textarea>
        </div>
    </div>
    <div class="col">
        <div class="form-group">
        <label for="child-medical_notes">Medical Notes</label>
        <textarea name="child-medical_notes" cols="20" rows="3" class="textarea form-control" id="id_child-allergies"></textarea>
        </div>
    </div>
</div>

directory/templates/directory/home.html
{% extends 'base.html' %}

{% block title %}
Welcome
{% endblock title %}

{% block content %}
<div class="container">
    <div class="row">
      <div class="container">
        <h1 class="text-center">Welcome to HomeSchool Connections</h1>
      </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card search-card parent-search-card" style="width: 18rem;">
                <div class="card-header">
                  Parents
                </div>
                <div class="container">
                  <div class="row">
                    <input placeholder="&#xf002 Parent Search" type="text" name="parent_search" id="parent_search" class="form-control search-glass">
                  </div>
                </div>
                <ul class="list-group list-group-flush">
                  {% for parent in parents %}
                    <li class="list-group-item"><a href="{% url 'view-object' obj_type='parent' pk=parent.pk %}">{{parent}}</a></li>
                  {% empty %}
                    <li class="list-group-item">No Families Registered</li>
                  {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="card child-search-card search-card" style="width: 18rem;">
                <div class="card-header">
                  Children
                </div>
                <div class="container">
                  <div class="row">
                    <input placeholder="&#xf002 Child Search" type="text" name="child_search" id="child_search" class="form-control search-glass">
                  </div>
                </div>
                <ul class="list-group list-group-flush">
                  {% for child in children %}
                    <li class="list-group-item"><a href="{% url 'view-object' obj_type='child' pk=child.pk %}">{{child}}</a></li>
                  {% empty %}
                    <li class="list-group-item">No Families Registered</li>
                  {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 18rem;">
                <div class="card-header">
                  Volunteers
                </div>
                <ul class="list-group list-group-flush">
                  {% for k, c in volunteer_types.items %}
                    <li class="list-group-item d-flex justify-content-between align-items-center"><a href="{% url 'view-volunteers' vtype=k %}">{{k}} </a><span class"badge badge-primary badge-pill">{{c}}</span></li>
                  {% empty %}
                    <li class="list-group-item">No Volunteers Registered</li>
                  {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script>
  $(document).ready(function(){
      $('.search-glass').keyup(function(){
          let search = $(this).val().toUpperCase()
          let search_box = $(this)
          let card = $(search_box).closest('.card')[0]
          let li = $(card).find('li > a')
          li.each(function(){
            if (search.length > 0) {
              if ($(this).text().toUpperCase().indexOf(search) == -1 ){
                $(this).parent().addClass('d-none')
              } else {
                $(this).parent().removeClass('d-none')
              }
            }
            else {
              $(this).parent().removeClass('d-none')
            }
          })
      })
  })
</script>
{% endblock javascript %}

directory/templates/directory/parent-form.html
<div class="row">
    <div class="col">
            <div class="form-group">
                <label for="id_parent-first_name">First Name<span class="asteriskField">*</span></label>
                <input type="text" name="parent-first_name" maxlength="50"  class="textinput textInput form-control" id="id_parent-first_name" aria-describedby="FirstName" placeholder="Enter First Name">
            </div>
    </div>
    <div class="col">
            <div class="form-group">
                <label for="id_parent-last_name">Last Name<span class="asteriskField">*</span></label>
                <input type="text" name="parent-last_name" maxlength='60' class="textinput textInput form-control" id="id_parent-last_name" aria-describedby="LastName" placeholder="Enter Last Name">
            </div>
    </div>
    <div class="col">
            <div class="form-group">
                <label for="id_parent-participation_level">Participation Level<span class="asteriskField">*</span></label>
                <select name="parent-participation_level" class="select form-control" id="id_parent-participation_level"> 
                    <option value="" selected="">---------</option> <option value="a">All-In</option> 
                    <option value="b">Email Me</option> <option value="c">Usually Busy</option>
                </select> 
            </div>
    </div>
</div>
<div class="row">
    <div class="col">
            <div class="form-group">
                <label for="id_parent-phone_number">Phone Number</label>
                <input type="tel" name="id_parent-phone_number" maxlength="128" class="textinput textInput form-control" id="id_parent-phone_number" placeholder="Enter Phone Number"> 
            </div>
    </div>
    <div class="col">
            <div class="form-group">
                <label for="id_parent-email">Email Address</label>
                <input type="email" name="parent-email" maxlength="254" class="emailinput form-control" id="id_parent-email" placeholder="Enter Email Address"> 
            </div>
    </div>
    <div class="col">
            <div class="form-group">
                <label for="id_parent-best_contact_option">Best Contact <span class="asteriskField">*</span></label>
                <select name="parent-best_contact_option" class="select form-control" id="id_parent-best_contact_option"> 
                    <option value="" selected="">---------</option> 
                    <option value="e">Email</option> 
                    <option value="p">Phone</option> 
                    <option value="t">Text</option>
                </select> 
            </div>
    </div>
    </div>
    <div class="row">
    <div class="col">
        <div class="form-group">
            <label for="id_parent-volunteering_type_1">Volunteering 1 <span class="asteriskField">*</span></label>
            <select name="parent-volunteering_type_1" class="select form-control" id="id_parent-volunteering_type_1"> 
                <option value="" selected>---------</option>

                <option value="Ft">Field Trips</option>

                <option value="T">Tutoring</option>

                <option value="S">Small Snack</option>

                <option value="SG">Study Groups</option>
            </select> 
        </div>
    </div>
    <div class="col">
        <div class="form-group">
            <label for="id_parent-volunteering_type_2">Volunteering 2 <span class="asteriskField">*</span></label>
            <select name="parent-volunteering_type_2" class="select form-control" id="id_parent-volunteering_type_2"> 
                <option value="" selected>---------</option>

                <option value="Ft">Field Trips</option>

                <option value="T">Tutoring</option>

                <option value="S">Small Snack</option>

                <option value="SG">Study Groups</option>
            </select> 
        </div>                    
    </div>
</div>

directory/templates/directory/view_contact.html
{% extends 'base.html' %}

{% block title %}
Welcome
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-header" >
        <div class="card-title">Viewing Parent: {{parent}}</div>
    </div>
    <div  class="card-body">
        <div class="container">
            <div class="row">
                <div class="container">
                    <div class="col">
                        <div class="row">
                            <h4>User Information</h4>
                        </div>
                        <div class="row">
                            <h6>Member Since: {{parent.created_at|date:"M Y"}}</h6>
                        </div>
                    </div>
                </div>
            </div>
            <hr class='small-break'>
            <div class="row">
                    <div class="col-sm-4">
                        {% if parent.best_contact_option == 'e' %}
                        <div class="row">Best Contact Option: {{parent.email}}</div>
                        {% endif %}
                        {% if parent.best_contact_option == 'p' %}
                        <div class="row">Best Contact Option: {{parent.phone}} Call</div>
                        {% endif %}
                        {% if parent.best_contact_option == 't' %}}
                        <div class="row">Best Contact Option: {{parent.phone}} Text</div>
                        {% endif %}
                        <div class="row">Participation Level: {{parent.get_participation_level_display}}</div>
                        <div class="row">Volunteering Preferences: {{parent.get_volunteering_type_1_display}}</div>
                        <div class="row">Volunteering Preferences: {{parent.get_volunteering_type_2_display}}</div>
                    </div>
                    <div class="col-sm-8">
                        {% for child in parent.children.all %}
                        <div class="row">
                            <div class="container">
                                <div class="card">
                                    <div class="card-header">
                                        <div class="card-title">{{child.child_name}}</div>
                                    </div>
                                    <div class="card-body">
                                        <div class="container">
                                            <div class="row">Child Age: {{child.age}}</div>
                                            {% if child.allergies|length > 0 %}
                                            <div class="row">Allergies: {{child.allergies}}</div>
                                            {% else %}
                                            <div class="row">Allergies: None</div>
                                            {% endif %}
                                            {% if child.medial_notes|length > 0 %}
                                            <div class="row">Medical Notes: {{child.medical_notes}}</div>
                                            {% else %}
                                            <div class="row">Medical Notes: None</div>
                                            {% endif %}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    </div>
            </div>
        </div>
    </div>
    <div class="card-footer">
        <a href="{% url 'home' %}" class="btn btn-sm btn-primary pull-right">Return</a>
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script>
  $(document).ready(function(){
      $('.search-glass').keyup(function(){
          let search = $(this).val().toUpperCase()
          let search_box = $(this)
          let card = $(search_box).closest('.card')[0]
          let li = $(card).find('li > a')
          li.each(function(){
            if (search.length > 0) {
              if ($(this).text().toUpperCase().indexOf(search) == -1 ){
                $(this).parent().addClass('d-none')
              } else {
                $(this).parent().removeClass('d-none')
              }
            }
            else {
              $(this).parent().removeClass('d-none')
            }
          })
      })
  })
</script>
{% endblock javascript %}

directory/templates/directory/volunteer_list.html
{% extends 'base.html' %}

{% block title %}
Welcome
{% endblock title %}

{% block content %}
<div class="card">
    <div class="card-header" >
        <div class="card-title">Volunteers for : {{type}}</div>
    </div>
    <div  class="card-body">
        <div class="container">
            <ul class="list-group list-group-flush">
                {% for parent in parents %}
                <li class="list-group-item">
                    <div class="container">
                        <div class="row">
                            <div class="col">
                                <a href="{% url 'view-object' obj_type='parent' pk=parent.pk %}">{{parent}}</a>
                            </div>
                            <div class="col">
                                {% if parent.best_contact_option == 'e' %}
                                Email: {{parent.email}}
                                {% endif %}
                                {% if parent.best_contact_option == 'p' %}
                                Phone: {{parent.phone_number}}
                                {% endif %}
                                {% if parent.best_contact_option == 't' %}
                                Text: {{parent.phone_number}}
                                {% endif %}
                            </div>
                            <div class="col">
                                <span>{{parent.get_participation_level_display}}</span>
                            </div>
                        </div>
                    </div>
                </li>
                {% empty %}
                <li class="list-group-item">No Families Registered</li>
                {% endfor %}
            </ul>
        </div>
    </div>
    <div class="card-footer">
        <a class="btn btn-primary pull-right" href="{% url 'home' %}">Home</a>
    </div>
</div>

{% endblock content %}

{% block javascript %}
<script>
  $(document).ready(function(){
      $('.search-glass').keyup(function(){
          let search = $(this).val().toUpperCase()
          let search_box = $(this)
          let card = $(search_box).closest('.card')[0]
          let li = $(card).find('li > a')
          li.each(function(){
            if (search.length > 0) {
              if ($(this).text().toUpperCase().indexOf(search) == -1 ){
                $(this).parent().addClass('d-none')
              } else {
                $(this).parent().removeClass('d-none')
              }
            }
            else {
              $(this).parent().removeClass('d-none')
            }
          })
      })
  })
</script>
{% endblock javascript %}